version: "3.8"
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 8080:8080
    container_name: go-lesson
    tty: true
    volumes:
      - ./:/app
