version: "3.8"
services:
  golang:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 8080:8080
    container_name: go-lesson
    stdin_open: true
    tty: true
    volumes:
      - ../:/workspace/go_lesson

